# Generated by Django 4.2.7 on 2025-05-24 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediatrack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('serie', 'Serie'), ('pelicula', 'Película'), ('anime', 'Anime'), ('otro', 'Otro')], max_length=20)),
                ('enlace_plataforma', models.URLField(blank=True)),
                ('total_episodios', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medio',
                'verbose_name_plural': 'Medios',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
