# Generated by Django 4.2.7 on 2025-05-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatrack_app', '0002_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='media',
            name='total_episodios',
        ),
        migrations.AddField(
            model_name='media',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en minutos (solo para películas)', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='total_capitulos',
            field=models.PositiveIntegerField(blank=True, help_text='Número total de capítulos (solo para series y animes)', null=True),
        ),
    ]
