# Generated by Django 4.2.7 on 2025-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatrack_app', '0003_remove_media_duracion_remove_media_total_episodios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='imagen_url',
            field=models.URLField(blank=True, verbose_name='Enlace de Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='media',
            name='enlace_plataforma',
            field=models.URLField(blank=True, verbose_name='Enlace a Plataforma'),
        ),
    ]
