# Generated by Django 4.2.7 on 2025-05-25 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediatrack_app', '0004_media_imagen_url_alter_media_enlace_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='visto',
            field=models.BooleanField(default=False, help_text='Marcar como visto (solo para películas)'),
        ),
        migrations.CreateModel(
            name='SeguimientoEpisodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_episodio', models.PositiveIntegerField()),
                ('visto', models.BooleanField(default=False)),
                ('fecha_visto', models.DateTimeField(blank=True, null=True)),
                ('media', models.ForeignKey(limit_choices_to={'tipo__in': ['serie', 'anime']}, on_delete=django.db.models.deletion.CASCADE, related_name='episodios_vistos', to='mediatrack_app.media')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_episodios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Episodio',
                'verbose_name_plural': 'Seguimiento de Episodios',
                'ordering': ['media__nombre', 'numero_episodio'],
                'unique_together': {('media', 'usuario', 'numero_episodio')},
            },
        ),
    ]
