# Generated by Django 4.2.7 on 2025-05-25 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatrack_app', '0005_media_visto_seguimientoepisodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='calificacion_pelicula',
            field=models.PositiveIntegerField(blank=True, help_text='Calificación de 1 a 5 estrellas (solo para películas)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='media',
            name='comentario_pelicula',
            field=models.TextField(blank=True, help_text='Comentario opcional (solo para películas)'),
        ),
        migrations.AddField(
            model_name='seguimientoepisodio',
            name='calificacion',
            field=models.PositiveIntegerField(blank=True, help_text='Calificación de 1 a 5 estrellas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='seguimientoepisodio',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
